services:
    form.type.ueditor:
        class: Jims\EditorHubBundle\Form\UeditorType
        tags:
            - { name: form.type, alias: ueditor  }

    form.type.umeditor:
        class: Jims\EditorHubBundle\Form\UmeditorType
        tags:
            - { name: form.type, alias: umeditor  }

    ueditor.uploader:
        class: Jims\EditorHubBundle\Service\UeditorUploader

    umeditor.uploader:
        class: Jims\EditorHubBundle\Service\UmeditorUploader